{{- if .Values.podDisruptionBudget.enabled }}
{{- range $name := list "frontend" "hello-service" "profile-service" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}
  labels:
    {{- include "mern.labels" $ | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ $name }}
---
{{- end }}
{{- end }}
